micronaut:
  application:
    name: cursotech
datasources:
  default:
    url: jdbc:mysql://localhost:3307/meubanco
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
